/**
 * Single source of truth for personal identity, career data, and skills.
 * UI chrome strings live in `src/lib/dictionaries/{en,pt}.ts`.
 *
 * Content mirrors the source CV (Felipe Gomes — Backend & AI Engineer).
 */

export type LucideIconName = string;

export type LocalizedString = {
  en: string;
  pt: string;
};

export type SkillItem = {
  name: string;
  icon: LucideIconName;
};

/** Narrative beats shown as the About timeline. */
export type JourneyEntry = {
  id: string;
  title: LocalizedString;
  period: LocalizedString;
  description: LocalizedString;
};

/** Real roles shown in the Experience section and on the resume. */
export type ExperienceEntry = {
  id: string;
  role: LocalizedString;
  org: LocalizedString;
  period: LocalizedString;
  description: LocalizedString;
  tags?: readonly string[];
};

export type EducationKind = "university" | "course" | "certificate";

export type EducationEntry = {
  id: string;
  kind: EducationKind;
  title: LocalizedString;
  institution: LocalizedString;
  period: LocalizedString;
  description: LocalizedString;
};

export type CertificationEntry = {
  id: string;
  title: LocalizedString;
  year: string;
};

export type SpokenLanguage = {
  name: LocalizedString;
  level: LocalizedString;
};

export type ExtensionEntry = {
  id: string;
  name: string;
  repository: string;
  technologies: readonly string[];
  type: LocalizedString;
  description: LocalizedString;
  capabilities: {
    en: readonly string[];
    pt: readonly string[];
  };
  previewAlt: LocalizedString;
};

/** Hand-written project cards: the Featured grid no longer depends on GitHub ranking. */
export type FeaturedProject = {
  id: string;
  name: string;
  language: string;
  description: LocalizedString;
  technologies: readonly string[];
  demo?: string;
  /** Omitted for private repositories: the card then shows only the demo. */
  repository?: string;
};

export const siteConfig = {
  name: "Felipe Gomes",
  fullName: "Felipe Damasceno Reis Gomes",
  githubUsername: "lipereis",
  email: "felipedrg02@gmail.com",
  phone: "(21) 9 7455-4444",
  linkedin: "https://www.linkedin.com/in/felipe-gomes-0220b7247/",
  linkedinHandle: "linkedin.com/in/felipe-gomes-0220b7247",
  /** Locale-aware resume PDFs (generated by `npm run generate-resume`). */
  resumeUrls: {
    en: "/resume-en.pdf",
    pt: "/resume-pt.pdf",
  },
  /** Legacy default — English. Prefer `resumeUrls[locale]`. */
  resumeUrl: "/resume-en.pdf",
  siteUrl: "https://lipereis.github.io/engineer-portfolio",
  basePath: "/engineer-portfolio",
  location: "Rio de Janeiro — RJ",
  headline: "Backend & AI Engineer · Full-stack (React / Next.js / Node.js)",
  socials: {} as Record<string, never>,

  /** Repos excluded from ranking (e.g. profile README-only). */
  repoDenylist: ["lipereis", "engineer-portfolio", "AmzScope", "video-portfolio"] as const,

  /** Earlier career work, linked from About instead of sitting in the engineering grid. */
  videoPortfolioUrl: "https://lipereis.github.io/video-portfolio/",

  /**
   * Always show first in Featured (then fill remaining slots by score).
   * Names must match GitHub repo names exactly (case-insensitive match).
   */
  featuredPins: ["TrainFlow", "CineOps", "RAGCore", "spoileralert"] as const,

  /** Prettier labels for repos whose GitHub name isn't cased the way I write it. */
  repoDisplayNames: {
    spoileralert: "SpoilerAlert",
  } as const,

  featuredProjects: [
    {
      id: "hookedit",
      name: "HookEdit",
      language: "TypeScript",
      description: {
        en: "AI editor for vertical video. Upload a clip and it transcribes with word-level timestamps (Whisper), builds dynamic captions, and uses Gemini to suggest retention edits: cuts, B-roll, sound effects, and a hook review. Exports the final clip through ffmpeg.",
        pt: "Editor de vídeo vertical com IA. Você sobe o clipe e ele transcreve com timestamp por palavra (Whisper), monta legendas dinâmicas e usa o Gemini para sugerir edições de retenção: cortes, B-roll, efeitos sonoros e avaliação do hook. Exporta o clipe final via ffmpeg.",
      },
      technologies: ["Next.js", "FastAPI", "faster-whisper", "Gemini", "ffmpeg"],
      demo: "https://hookedit.vercel.app/",
    },
    {
      id: "metis",
      name: "Metis",
      language: "Python",
      description: {
        en: "Content pipeline built as a demonstration project. Turns a transcript into hooks, a video script table, and per-platform captions, and runs a trend radar over RSS feeds that sends approval cards to Slack or Telegram. LLM replies are validated against Pydantic schemas; tests run with a fake model.",
        pt: "Pipeline de conteúdo feito como projeto de demonstração. Transforma uma transcrição em hooks, tabela de roteiro e legendas por plataforma, e roda um radar de tendências sobre feeds RSS que envia cartões de aprovação para Slack ou Telegram. As respostas do LLM são validadas com schemas Pydantic; os testes rodam com um modelo simulado.",
      },
      technologies: ["Python", "Pydantic", "LLM APIs", "RSS", "Webhooks"],
      repository: "https://github.com/lipereis/metis-content-strategist",
    },
    {
      id: "trainflow",
      name: "TrainFlow",
      language: "TypeScript",
      description: {
        en: "AI-powered operating system for personal trainers: trainer and client accounts, invite flow, workout templates, and client management in a Turborepo monorepo.",
        pt: "Sistema operacional com IA para personal trainers: contas de treinador e aluno, fluxo de convite, modelos de treino e gestão de alunos em um monorepo Turborepo.",
      },
      technologies: ["Next.js", "PostgreSQL", "Prisma", "Clerk", "Turborepo"],
      demo: "https://trainflow-chi.vercel.app",
      repository: "https://github.com/lipereis/TrainFlow",
    },
    {
      id: "ragcore",
      name: "RAGCore",
      language: "Python",
      description: {
        en: "Local hybrid RAG engine: PDF parsing with pdfplumber, vector search in Chroma combined with BM25 keyword search, FlashRank re-ranking, and answers from Gemini Flash.",
        pt: "Motor de RAG híbrido local: leitura de PDF com pdfplumber, busca vetorial no Chroma combinada com busca por palavra-chave BM25, re-ranking com FlashRank e respostas do Gemini Flash.",
      },
      technologies: ["Python", "Chroma", "BM25", "FlashRank", "Gemini"],
      repository: "https://github.com/lipereis/RAGCore",
    },
    {
      id: "supportflow-ai",
      name: "SupportFlow-AI",
      language: "Python",
      description: {
        en: "Customer support platform for a fictional store: a LangGraph agent answers from a RAG knowledge base behind a FastAPI service and escalates to a human when it should.",
        pt: "Plataforma de atendimento para uma loja fictícia: um agente em LangGraph responde a partir de uma base RAG atrás de um serviço FastAPI e escala para um humano quando necessário.",
      },
      technologies: ["Python", "LangGraph", "FastAPI", "RAG", "Docker"],
      repository: "https://github.com/lipereis/SupportFlow-AI",
    },
    {
      id: "terminalmind",
      name: "TerminalMind",
      language: "Python",
      description: {
        en: "Research assistant for the terminal. Queries an LLM with strict structured outputs (Pydantic), grounds answers in locally ingested notes, cites the chunks it used, and keeps session history.",
        pt: "Assistente de pesquisa no terminal. Consulta um LLM com saídas estruturadas estritas (Pydantic), fundamenta as respostas em notas ingeridas localmente, cita os trechos usados e guarda o histórico da sessão.",
      },
      technologies: ["Python", "Structured Outputs", "Pydantic", "Rich"],
      repository: "https://github.com/lipereis/TerminalMind",
    },
    {
      id: "cineops",
      name: "CineOps",
      language: "TypeScript",
      description: {
        en: "Film production tool that ties the shooting stripboard to the budget: drag a scene onto a shooting day and the budget recalculates in the same transaction.",
        pt: "Ferramenta de produção de cinema que liga o stripboard de filmagem ao orçamento: arraste uma cena para uma diária e o orçamento é recalculado na mesma transação.",
      },
      technologies: ["Next.js", "PostgreSQL", "Prisma", "dnd-kit"],
      repository: "https://github.com/lipereis/CineOps",
    },
    {
      id: "spoileralert",
      name: "SpoilerAlert",
      language: "Python",
      description: {
        en: "Turns a year of Letterboxd diary entries into a cinema recap: deterministic stats, optional TMDB enrichment, and six shareable 1080×1920 cards.",
        pt: "Transforma um ano de diário do Letterboxd em uma retrospectiva de cinema: estatísticas determinísticas, enriquecimento opcional via TMDB e seis cards 1080×1920 para compartilhar.",
      },
      technologies: ["Python", "Letterboxd", "TMDB"],
      repository: "https://github.com/lipereis/spoileralert",
    },
    {
      id: "aporte",
      name: "Aporte",
      language: "TypeScript",
      description: {
        en: "Personal finance tracker in Brazilian Portuguese: income and expenses, interactive spending charts, and monthly budgets per category.",
        pt: "Controle financeiro pessoal em português: receitas e despesas, gráficos interativos de gastos e orçamentos mensais por categoria.",
      },
      technologies: ["Next.js", "Prisma", "Neon Postgres"],
      repository: "https://github.com/lipereis/Aporte",
    },
    {
      id: "bizu-do-busao",
      name: "Bizu do Busão",
      language: "TypeScript",
      description: {
        en: "Real-time tracker for the city buses of Rio de Janeiro. Consumes the open data API from the city, processes the coordinates in an async worker, stores them in MySQL, and shows the fleet on an interactive map.",
        pt: "Rastreador em tempo real dos ônibus urbanos do Rio de Janeiro. Consome a API de dados abertos da prefeitura, processa as coordenadas em um worker assíncrono, armazena em MySQL e mostra a frota em um mapa interativo.",
      },
      technologies: ["TypeScript", "MySQL", "Open data API"],
      repository: "https://github.com/lipereis/Bizu-do-Busao",
    },
  ] as const satisfies readonly FeaturedProject[],

  extensions: [
    {
      id: "amzscope",
      name: "AmzScope",
      repository: "https://github.com/lipereis/AmzScope",
      technologies: ["JavaScript", "CSS", "Chrome Extension API"],
      type: {
        en: "Chrome Extension · Manifest V3",
        pt: "Extensão Chrome · Manifest V3",
      },
      description: {
        en: "Amazon Brazil product analytics, injected directly into the product page. AmzScope identifies the ASIN and estimates monthly sales, revenue, Amazon commission, and net earnings without interrupting the research workflow.",
        pt: "Análises de produtos da Amazon Brasil, injetadas diretamente na página do produto. O AmzScope identifica o ASIN e estima vendas mensais, receita, comissão da Amazon e ganhos líquidos sem interromper o fluxo de pesquisa.",
      },
      capabilities: {
        en: [
          "Automatic ASIN detection",
          "Monthly sales estimates",
          "Gross and net revenue projections",
          "Estimated Amazon commission",
        ],
        pt: [
          "Detecção automática do ASIN",
          "Estimativas de vendas mensais",
          "Projeções de receita bruta e líquida",
          "Comissão estimada da Amazon",
        ],
      },
      previewAlt: {
        en: "Illustrative AmzScope panel showing sample ASIN, sales, revenue, commission, and net earnings.",
        pt: "Painel ilustrativo do AmzScope com exemplos de ASIN, vendas, receita, comissão e ganhos líquidos.",
      },
    },
  ] as const satisfies readonly ExtensionEntry[],

  about: {
    en: "I'm Felipe Gomes — moving from communication and audiovisual work into software, focused on backend and AI engineering. My foundation is storytelling, production, and content operations; today I point that same discipline at building digital products. I'm self-taught in JavaScript, React, Node.js, and Python, with published projects (an AI editor for vertical video, plus tooling built on retrieval, vector search, and re-ranking) and constant practice in version control and deployment. I'm looking for a Backend / AI Engineer role where product reasoning, delivery discipline, and growing full-stack depth all count.",
    pt: "Sou Felipe Gomes — em transição da comunicação e do audiovisual para software, com foco em backend e engenharia de IA. Minha base é storytelling, produção e gestão de conteúdo; hoje aplico essa mesma disciplina na construção de produtos digitais. Sou autodidata em JavaScript, React, Node.js e Python, com projetos publicados (um editor de vídeo vertical com IA e ferramentas com retrieval, busca vetorial e re-ranking) e prática constante de versionamento e deploy. Busco uma vaga de Backend / AI Engineer onde raciocínio de produto, disciplina de entrega e profundidade full-stack crescente contem juntos.",
  } satisfies LocalizedString,

  /** About-section timeline: the arc, not job history. */
  journey: [
    {
      id: "audiovisual",
      title: {
        en: "Communication & Audiovisual",
        pt: "Comunicação & Audiovisual",
      },
      period: { en: "Foundation", pt: "Base" },
      description: {
        en: "A Social Communication degree at PUC-Rio plus years of editing, producing, and running content. Pacing, narrative, and finishing discipline — the habits I still bring to product work.",
        pt: "Graduação em Comunicação Social na PUC-Rio e anos editando, produzindo e gerindo conteúdo. Ritmo, narrativa e disciplina de acabamento — hábitos que ainda levo para produto.",
      },
    },
    {
      id: "learning-code",
      title: {
        en: "Learning to Build",
        pt: "Aprendendo a Construir",
      },
      period: { en: "Growth", pt: "Crescimento" },
      description: {
        en: "Self-taught from HTML, CSS, and JavaScript into React, Next.js, TypeScript, and Node.js. Shipped every step in public on GitHub instead of collecting tutorials.",
        pt: "Autodidata de HTML, CSS e JavaScript até React, Next.js, TypeScript e Node.js. Publiquei cada etapa no GitHub em vez de acumular tutoriais.",
      },
    },
    {
      id: "backend-ai",
      title: {
        en: "Backend & AI Engineering",
        pt: "Backend & Engenharia de IA",
      },
      period: { en: "Current", pt: "Atual" },
      description: {
        en: "Building real systems: HookEdit, an AI editor for vertical video (Whisper + Gemini + ffmpeg), a local hybrid RAG engine (Chroma + BM25 + FlashRank + Gemini), and an AI operating system for personal trainers. REST APIs, retrieval pipelines, and prompt engineering.",
        pt: "Construindo sistemas reais: o HookEdit, um editor de vídeo vertical com IA (Whisper + Gemini + ffmpeg), um motor RAG híbrido local (Chroma + BM25 + FlashRank + Gemini) e um sistema operacional com IA para personal trainers. APIs REST, pipelines de retrieval e prompt engineering.",
      },
    },
    {
      id: "goals",
      title: {
        en: "Backend / AI Engineer Role",
        pt: "Vaga de Backend / AI Engineer",
      },
      period: { en: "Next", pt: "Próximo" },
      description: {
        en: "Join a team shipping real products — owning backend services and AI features, with the frontend depth to carry a feature end to end.",
        pt: "Entrar em um time que entrega produtos reais — cuidando de serviços backend e features de IA, com profundidade de frontend para levar uma feature ponta a ponta.",
      },
    },
  ] as const satisfies readonly JourneyEntry[],

  /** Professional experience to date (communication & audiovisual). */
  experience: [
    {
      id: "nossoolharcarioca",
      role: {
        en: "Social Media / Video Editor / Videomaker",
        pt: "Social Media / Editor de Vídeo / Videomaker",
      },
      org: {
        en: "Nossoolharcarioca — Freelance",
        pt: "Nossoolharcarioca — Freelancer",
      },
      period: { en: "2025", pt: "2025" },
      description: {
        en: "Planned, produced, and edited video content for Instagram, focused on storytelling and engagement.",
        pt: "Planejamento, produção e edição de conteúdo em vídeo para Instagram, com foco em storytelling e engajamento.",
      },
      tags: ["Instagram", "Premiere Pro", "Storytelling"],
    },
    {
      id: "coreboyshubclips",
      role: {
        en: "Social Media — TikTok & YouTube Shorts",
        pt: "Social Media — TikTok e YouTube Shorts",
      },
      org: { en: "Coreboyshubclips", pt: "Coreboyshubclips" },
      period: { en: "2024", pt: "2024" },
      description: {
        en: "Curated, edited, and published short-form video; tracked performance and iterated on what worked.",
        pt: "Curadoria, edição e publicação de vídeos curtos; monitoramento de desempenho e iteração sobre o que funcionava.",
      },
      tags: ["TikTok", "Shorts", "Analytics"],
    },
    {
      id: "ladobdacena",
      role: {
        en: "Digital Content Creator",
        pt: "Criador de Conteúdo Digital",
      },
      org: {
        en: "@ladobdacena — TikTok & Substack",
        pt: "@ladobdacena — TikTok e Substack",
      },
      period: { en: "2023", pt: "2023" },
      description: {
        en: "Produced content on cinema and audiovisual culture; wrote articles and newsletters; managed the community.",
        pt: "Produção de conteúdo sobre cinema e audiovisual; redação de artigos e newsletters; gestão de comunidade.",
      },
      tags: ["Substack", "Writing", "Community"],
    },
    {
      id: "puc-editing-intern",
      role: { en: "Intern — Editing Suites", pt: "Estagiário — Ilhas de Edição" },
      org: { en: "PUC-Rio", pt: "PUC-Rio" },
      period: { en: "Aug 2023 — Feb 2024", pt: "Ago/2023 — Fev/2024" },
      description: {
        en: "Edited and finished audiovisual projects, organized post-production workflows, and gave technical support to students and faculty.",
        pt: "Edição e finalização de projetos audiovisuais, organização de fluxos de pós-produção e suporte técnico a alunos e professores.",
      },
      tags: ["Post-production", "Workflow", "Support"],
    },
  ] as const satisfies readonly ExperienceEntry[],

  education: [
    {
      id: "puc-rio",
      kind: "university",
      title: {
        en: "B.A. in Social Communication",
        pt: "Comunicação Social",
      },
      institution: {
        en: "Pontifical Catholic University of Rio de Janeiro (PUC-Rio)",
        pt: "Pontifícia Universidade Católica do Rio de Janeiro (PUC-Rio)",
      },
      period: {
        en: "Completed June 2024",
        pt: "Conclusão: Junho/2024",
      },
      description: {
        en: "Narrative, media production, and audience thinking — the base I now apply to product and engineering work.",
        pt: "Narrativa, produção de mídia e pensamento de audiência — a base que agora aplico em produto e engenharia.",
      },
    },
    {
      id: "datacamp",
      kind: "course",
      title: { en: "Courses in progress", pt: "Cursos em andamento" },
      institution: { en: "DataCamp", pt: "DataCamp" },
      period: { en: "In progress", pt: "Em andamento" },
      description: {
        en: "Currently enrolled and studying on DataCamp.",
        pt: "Atualmente matriculado e estudando no DataCamp.",
      },
    },
    {
      id: "coursera",
      kind: "course",
      title: { en: "Courses in progress", pt: "Cursos em andamento" },
      institution: { en: "Coursera", pt: "Coursera" },
      period: { en: "In progress", pt: "Em andamento" },
      description: {
        en: "Currently enrolled and studying on Coursera.",
        pt: "Atualmente matriculado e estudando no Coursera.",
      },
    },
    {
      id: "origamid",
      kind: "course",
      title: {
        en: "Web Design & Frontend Fundamentals",
        pt: "Web Design & Fundamentos de Frontend",
      },
      institution: {
        en: "Origamid (self-paced)",
        pt: "Origamid (autodidata)",
      },
      period: { en: "Completed modules", pt: "Módulos concluídos" },
      description: {
        en: "JavaScript, React, Backend with Node.js, and Tailwind CSS course tracks.",
        pt: "Trilhas de JavaScript, React, Backend com Node.js e Tailwind CSS.",
      },
    },
    {
      id: "freecodecamp",
      kind: "certificate",
      title: {
        en: "Python & Full Stack tracks",
        pt: "Trilhas de Python & Full Stack",
      },
      institution: { en: "freeCodeCamp", pt: "freeCodeCamp" },
      period: { en: "Certifications", pt: "Certificações" },
      description: {
        en: "Python fundamentals and full-stack web development coursework.",
        pt: "Fundamentos de Python e desenvolvimento web full-stack.",
      },
    },
    {
      id: "self-taught",
      kind: "course",
      title: {
        en: "Self-taught Software Path",
        pt: "Trilha Autodidata em Software",
      },
      institution: { en: "Independent study", pt: "Estudo independente" },
      period: { en: "Continuous", pt: "Contínuo" },
      description: {
        en: "React, Next.js, TypeScript, and AI tooling learned by shipping public GitHub projects.",
        pt: "React, Next.js, TypeScript e ferramentas de IA aprendidos publicando projetos no GitHub.",
      },
    },
  ] as const satisfies readonly EducationEntry[],

  /** Shorter credentials rendered as a chip list under Education. */
  certifications: [
    {
      id: "edicao-negocios",
      title: { en: "Editing & Business", pt: "Edição e Negócios" },
      year: "2023",
    },
    {
      id: "comercializacao",
      title: {
        en: "Audiovisual Sales & Distribution",
        pt: "Comercialização e Distribuição para o Audiovisual",
      },
      year: "2024",
    },
    {
      id: "legislacao",
      title: {
        en: "Audiovisual Law & Business",
        pt: "Legislação e Negócios para o Audiovisual",
      },
      year: "2024",
    },
    {
      id: "pedagogica",
      title: {
        en: "Pedagogical Training: Entrepreneurship & BNCC",
        pt: "Formação Pedagógica: Empreendedorismo e BNCC",
      },
      year: "2024",
    },
    {
      id: "office365",
      title: { en: "Office 365", pt: "Office 365" },
      year: "2022",
    },
  ] as const satisfies readonly CertificationEntry[],

  spokenLanguages: [
    {
      name: { en: "Portuguese", pt: "Português" },
      level: { en: "Native", pt: "Nativo" },
    },
    {
      name: { en: "English", pt: "Inglês" },
      level: { en: "Advanced", pt: "Avançado" },
    },
    {
      name: { en: "Spanish", pt: "Espanhol" },
      level: { en: "Advanced", pt: "Avançado" },
    },
  ] as const satisfies readonly SpokenLanguage[],

  skills: {
    ai: [
      { name: "RAG (Retrieval-Augmented Generation)", icon: "Bot" },
      { name: "Vector search (Chroma)", icon: "Boxes" },
      { name: "Keyword search (BM25)", icon: "Search" },
      { name: "Re-ranking (FlashRank)", icon: "ArrowUpDown" },
      { name: "Gemini / Claude / OpenAI APIs", icon: "Sparkles" },
      { name: "Prompt engineering", icon: "MessageSquareCode" },
    ] as const satisfies readonly SkillItem[],
    backend: [
      { name: "Node.js", icon: "Server" },
      { name: "REST APIs", icon: "Network" },
      { name: "Next.js Route Handlers", icon: "Route" },
      { name: "Auth & API integration", icon: "KeyRound" },
    ] as const satisfies readonly SkillItem[],
    languages: [
      { name: "TypeScript", icon: "FileCode2" },
      { name: "JavaScript", icon: "Braces" },
      { name: "Python", icon: "Binary" },
      { name: "SQL", icon: "Table2" },
    ] as const satisfies readonly SkillItem[],
    frontend: [
      { name: "React", icon: "Atom" },
      { name: "Next.js", icon: "Layers" },
      { name: "Tailwind CSS", icon: "Palette" },
      { name: "HTML / CSS", icon: "Code2" },
      { name: "Framer Motion", icon: "Sparkles" },
    ] as const satisfies readonly SkillItem[],
    databases: [
      { name: "PostgreSQL", icon: "Database" },
      { name: "SQLite", icon: "HardDrive" },
    ] as const satisfies readonly SkillItem[],
    tools: [
      { name: "Git / GitHub", icon: "GitBranch" },
      { name: "VS Code / Cursor", icon: "Terminal" },
      { name: "Vercel", icon: "Cloud" },
      { name: "Streamlit", icon: "LayoutDashboard" },
      { name: "Notion", icon: "NotebookPen" },
    ] as const satisfies readonly SkillItem[],
    design: [
      { name: "Figma", icon: "PenTool" },
      { name: "Video editing", icon: "Clapperboard" },
      { name: "UI craft", icon: "LayoutTemplate" },
    ] as const satisfies readonly SkillItem[],
  },
} as const;

export type SiteConfig = typeof siteConfig;
